import { useEffect, useMemo, useState } from "react";
import { BarChart3, Boxes, ChevronRight, CircleDollarSign, LayoutDashboard, LogOut, Menu, PackagePlus, Search, ShoppingBag, Sparkles, TicketPercent, Truck, Users, X } from "lucide-react";
import axiosInstance from "../utils/Axios";
import "./Admin.css";

const sections = [
  ["Overview", LayoutDashboard], ["Products", Boxes], ["Orders", ShoppingBag], ["Inventory", PackagePlus],
  ["Customers", Users], ["Promotions", TicketPercent], ["Reports", BarChart3], ["Delivery", Truck],
];
const emptyProduct = { title: "", description: "", price: "", originalPrice: "", category: "", image: "", stock: 0 };
const money = (n = 0) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
const getAdmin = () => { try { return JSON.parse(localStorage.getItem("vora_admin") || "null"); } catch { return null; } };

export default function Admin() {
  const [admin, setAdmin] = useState(getAdmin);
  const [login, setLogin] = useState({ email: "", password: "" });
  const [active, setActive] = useState("Overview");
  const [data, setData] = useState({ stats: {}, products: [], orders: [], users: [], promotions: [] });
  const [query, setQuery] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [mobile, setMobile] = useState(false); const [modal, setModal] = useState(null); const [form, setForm] = useState(emptyProduct);

  const auth = () => ({ headers: { Authorization: `Bearer ${admin?.token}` } });
  const load = async () => { try { setBusy(true); const { data: result } = await axiosInstance.get("/admin/dashboard", auth()); setData(result); setError(""); } catch (e) { if (e.response?.status === 401 || e.response?.status === 403) logout(); else setError(e.response?.data?.message || "Could not load dashboard"); } finally { setBusy(false); } };
  useEffect(() => { if (admin) load(); }, [admin?.token]);
  const signIn = async (e) => { e.preventDefault(); try { setBusy(true); setError(""); const { data: result } = await axiosInstance.post("/admin/login", login); const session = { token: result.token, ...result.admin }; localStorage.setItem("vora_admin", JSON.stringify(session)); setAdmin(session); } catch (e) { setError(e.response?.data?.message || "Admin login failed"); } finally { setBusy(false); } };
  const logout = () => { localStorage.removeItem("vora_admin"); setAdmin(null); };
  const products = useMemo(() => data.products.filter((p) => `${p.title} ${p.category}`.toLowerCase().includes(query.toLowerCase())), [data.products, query]);
  const totalStock = (p) => p.variants?.reduce((n, v) => n + Number(v.stock || 0), 0) || 0;
  const openProduct = (p) => { setForm(p ? { ...p, image: p.images?.[0] || "", stock: totalStock(p) } : emptyProduct); setModal(p ? "edit" : "add"); };
  const saveProduct = async (e) => { e.preventDefault(); const payload = { title: form.title, description: form.description, price: Number(form.price), originalPrice: Number(form.originalPrice || form.price), category: form.category, images: [form.image], isNew: modal === "add", onSale: Number(form.originalPrice) > Number(form.price), colors: ["Default"], sizes: ["One Size"], variants: [{ color: "Default", size: "One Size", stock: Number(form.stock) }], features: ["Quality checked"] }; try { setBusy(true); if (modal === "edit") await axiosInstance.patch(`/admin/products/${form._id}`, payload, auth()); else await axiosInstance.post("/admin/products", payload, auth()); setModal(null); await load(); } catch (e) { setError(e.response?.data?.message || "Could not save product"); } finally { setBusy(false); } };
  const removeProduct = async (id) => { if (!confirm("Delete this product permanently?")) return; await axiosInstance.delete(`/admin/products/${id}`, auth()); load(); };
  const setOrderStatus = async (id, orderStatus) => { await axiosInstance.patch(`/admin/orders/${id}/status`, { orderStatus }, auth()); load(); };
  const createPromo = async () => { const name = prompt("Campaign name"); if (!name) return; const code = prompt("Coupon code")?.trim().toUpperCase(); if (!code) return; const discount = Number(prompt("Discount percentage (1-100)", "10")); if (!discount || discount > 100) return setError("Enter a discount between 1 and 100"); try { await axiosInstance.post("/admin/promotions", { name, code, discount }, auth()); load(); } catch(e) { setError(e.response?.data?.message || "Could not create campaign"); } };
  const togglePromo = async (p) => { await axiosInstance.patch(`/admin/promotions/${p._id}`, { active: !p.active }, auth()); load(); };
  const removePromo = async (id) => { if (!confirm("Delete this campaign?")) return; await axiosInstance.delete(`/admin/promotions/${id}`, auth()); load(); };

  if (!admin) return <main className="admin-login"><section><div className="admin-mark"><Sparkles /> VORA / CONTROL</div><p className="login-kicker">Private workspace</p><h1>Run your store<br/>with clarity.</h1><p>Sign in with the administrator account created by <code>createAdmin.js</code>.</p><form onSubmit={signIn}><label>Email<input type="email" required value={login.email} onChange={(e) => setLogin({ ...login, email: e.target.value })}/></label><label>Password<input type="password" required value={login.password} onChange={(e) => setLogin({ ...login, password: e.target.value })}/></label>{error && <div className="admin-error">{error}</div>}<button disabled={busy}>{busy ? "Checking…" : "Enter dashboard"}<ChevronRight size={18}/></button></form><a href="/">← Return to store</a></section></main>;

  const renderContent = () => {
    if (active === "Overview") return <><div className="admin-hero"><div><span>MONDAY, 17 AUG</span><h1>Good day, {admin.name?.split(" ")[0]}.</h1><p>Here is what is moving in your store today.</p></div><button onClick={() => openProduct()}><PackagePlus size={18}/> New product</button></div><div className="stats"><Stat icon={CircleDollarSign} label="Revenue" value={money(data.stats.revenue)} note="All non-cancelled orders"/><Stat icon={ShoppingBag} label="Orders" value={data.stats.orders || 0} note="Across every channel"/><Stat icon={Boxes} label="Products" value={data.stats.products || 0} note={`${products.filter(p => totalStock(p) < 10).length} need attention`}/><Stat icon={Users} label="Customers" value={data.stats.customers || 0} note="Registered shoppers"/></div><div className="overview-grid"><section className="panel"><PanelTitle title="Recent orders" action={() => setActive("Orders")}/><OrderTable orders={data.orders.slice(0, 5)} onStatus={setOrderStatus}/></section><section className="panel"><PanelTitle title="Stock watch" action={() => setActive("Inventory")}/>{[...data.products].sort((a,b)=>totalStock(a)-totalStock(b)).slice(0,5).map(p=><div className="stock-row" key={p._id}><img src={p.images?.[0]} alt=""/><div><b>{p.title}</b><small>{p.category}</small></div><span className={totalStock(p)<10?"low":""}>{totalStock(p)} left</span></div>)}</section></div></>;
    if (["Products", "Inventory"].includes(active)) return <section className="panel full"><div className="table-tools"><div><h2>{active}</h2><p>{active === "Inventory" ? "Monitor availability across the catalog." : "Create, edit, and organize your catalog."}</p></div><div className="search"><Search size={17}/><input placeholder="Search catalog" value={query} onChange={e=>setQuery(e.target.value)}/></div><button onClick={()=>openProduct()}><PackagePlus size={17}/> Add product</button></div><div className="product-grid">{products.map(p=><article className="product-tile" key={p._id}><img src={p.images?.[0]} alt={p.title}/><div><small>{p.category}</small><h3>{p.title}</h3><b>{money(p.price)}</b><span className={totalStock(p)<10?"low pill":"pill"}>{totalStock(p)} in stock</span></div><footer><button onClick={()=>openProduct(p)}>Edit</button><button className="danger" onClick={()=>removeProduct(p._id)}>Delete</button></footer></article>)}</div></section>;
    if (active === "Orders" || active === "Delivery") return <section className="panel full"><div className="table-tools"><div><h2>{active}</h2><p>Track fulfilment and update each order in real time.</p></div></div><OrderTable orders={data.orders} onStatus={setOrderStatus}/></section>;
    if (active === "Customers") return <section className="panel full"><div className="table-tools"><div><h2>Customers</h2><p>Your registered customer community.</p></div></div><table><thead><tr><th>Customer</th><th>Email</th><th>Role</th><th>Joined</th></tr></thead><tbody>{data.users.map(u=><tr key={u._id}><td><b>{u.name}</b></td><td>{u.email}</td><td><span className="status">{u.role}</span></td><td>{new Date(u.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></section>;
    if (active === "Promotions") return <section className="panel full"><div className="table-tools"><div><h2>Campaign studio</h2><p>Create and control promotional coupon codes.</p></div><button onClick={createPromo}><TicketPercent size={17}/> Create campaign</button></div><table><thead><tr><th>Campaign</th><th>Code</th><th>Discount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.promotions?.length?data.promotions.map(p=><tr key={p._id}><td><b>{p.name}</b></td><td><code>{p.code}</code></td><td>{p.discount}%</td><td><span className="status">{p.active?"Active":"Paused"}</span></td><td><button onClick={()=>togglePromo(p)}>{p.active?"Pause":"Activate"}</button> · <button className="low" onClick={()=>removePromo(p._id)}>Delete</button></td></tr>):<tr><td colSpan="5" className="empty-cell">No campaigns yet. Create your first coupon.</td></tr>}</tbody></table></section>;
    return <section className="panel full"><div className="table-tools"><div><h2>Performance reports</h2><p>A live summary calculated from your store data.</p></div></div><div className="report-bars">{data.products.slice(0,8).map((p,i)=><div key={p._id}><span>{p.title}</span><i style={{width:`${Math.max(12,100-i*11)}%`}}/><b>{money(p.price)}</b></div>)}</div></section>;
  };
  return <div className="admin-shell"><aside className={mobile?"open":""}><div className="admin-mark"><Sparkles/> VORA / CONTROL</div><button className="close" onClick={()=>setMobile(false)}><X/></button><nav>{sections.map(([name,Icon])=><button className={active===name?"active":""} key={name} onClick={()=>{setActive(name);setMobile(false)}}><Icon size={19}/>{name}</button>)}</nav><div className="admin-user"><div>{admin.name?.[0]}</div><span><b>{admin.name}</b><small>{admin.email}</small></span><button onClick={logout} title="Logout"><LogOut size={18}/></button></div></aside><main className="admin-main"><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><b>{active}</b><span> / Store administration</span></div><button className="store-link" onClick={()=>location.href="/"}>View storefront ↗</button></header>{error&&<div className="admin-error banner">{error}</div>}<div className="admin-content">{busy&&!data.products.length?<div className="loader">Loading workspace…</div>:renderContent()}</div></main>{modal&&<div className="modal-backdrop"><form className="product-modal" onSubmit={saveProduct}><button type="button" className="modal-x" onClick={()=>setModal(null)}><X/></button><small>CATALOG EDITOR</small><h2>{modal==="add"?"Add a new product":"Update product"}</h2><div className="form-grid"><label>Product title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Price<input required type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Original price<input type="number" min="0" value={form.originalPrice} onChange={e=>setForm({...form,originalPrice:e.target.value})}/></label><label>Stock<input required type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label>Image URL<input required type="url" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></label><label className="wide">Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><footer><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="save" disabled={busy}>{busy?"Saving…":"Save product"}</button></footer></form></div>}</div>;
}

function Stat({icon:Icon,label,value,note}){return <article className="stat"><div><Icon/></div><span>{label}<b>{value}</b><small>{note}</small></span></article>}
function PanelTitle({title,action}){return <div className="panel-title"><h2>{title}</h2><button onClick={action}>View all <ChevronRight size={16}/></button></div>}
function OrderTable({orders,onStatus}){return <div className="table-scroll"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Date</th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={o._id}><td><b>#{o._id.slice(-6).toUpperCase()}</b></td><td>{o.userId?.name||o.shippingAddress?.fullName||"Guest"}<small>{o.userId?.email}</small></td><td>{money(o.totalAmount)}</td><td>{o.paymentStatus}</td><td><select value={o.orderStatus} onChange={e=>onStatus(o._id,e.target.value)}>{["PLACED","CONFIRMED","PROCESSING","SHIPPED","OUT_FOR_DELIVERY","DELIVERED","CANCELLED"].map(s=><option key={s}>{s}</option>)}</select></td><td>{new Date(o.createdAt).toLocaleDateString()}</td></tr>):<tr><td colSpan="6" className="empty-cell">No orders yet.</td></tr>}</tbody></table></div>}
